apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-Deployment
  template:
    metadata:
      labels:
        app: myapp-Deployment
    spec:
      containers:
      - name: my-repo
        image: 579385932895.dkr.ecr.us-east-1.amazonaws.com/my-repo
        imagePullSecrets:
          - name: ecr-secret
        ports:
        - containerPort: 80